apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cilium-etcd-watchdog.fullname" . }}
  namespace: {{ include "cilium-etcd-watchdog.namespace" . }}
  labels:
    {{- include "cilium-etcd-watchdog.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cilium-etcd-watchdog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cilium-etcd-watchdog.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cilium-etcd-watchdog.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
          - --cluster-bootstrap-grace-period={{ .Values.cluster.bootstrapGracePeriod }}
          - --cluster-name={{ .Values.cluster.name }}
          - --cluster-namespace={{ .Values.cluster.namespace }}
          - --etcd-client-dial-timeout={{ .Values.etcdClient.dialTimeout }}
          - --etcd-client-op-timeout={{ .Values.etcdClient.opTimeout }}
          - --log-level={{ .Values.logLevel }}
          - --max-quorum-status-check-failures={{ .Values.maxQuorumStatusCheckFailures }}
          - --polling-interval={{ .Values.pollingInterval }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "cilium-etcd-watchdog.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
