apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cilium-etcd-watchdog.fullname" . }}
  namespace: {{ include "cilium-etcd-watchdog.namespace" . }}
  labels:
    {{- include "cilium-etcd-watchdog.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cilium-etcd-watchdog.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cilium-etcd-watchdog.serviceAccountName" . }}
    namespace: {{ include "cilium-etcd-watchdog.namespace" . }}
