apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cilium-etcd-watchdog.fullname" . }}
  namespace: {{ include "cilium-etcd-watchdog.namespace" . }}
  labels:
    {{- include "cilium-etcd-watchdog.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - etcd.database.coreos.com
    resources:
      - etcdclusters
    verbs:
      - get
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
