{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cilium-etcd-watchdog.serviceAccountName" . }}
  namespace: {{ include "cilium-etcd-watchdog.namespace" . }}
  labels:
    {{- include "cilium-etcd-watchdog.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
